server:
  port: 8010
spring:
  cloud.config.server.health.enabled: true

info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    java:
      source: ${java.version}
      target: ${java.version}
